name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Restore Core.JsonSerializer
      run: dotnet restore ./Core.JsonSerializer.slnx

    - name: Build Core.JsonSerializer
      run: dotnet build ./Core.JsonSerializer.slnx --no-restore -c Release

    - name: Test Core.JsonSerializer
      run: dotnet test ./Core.JsonSerializer.slnx --no-restore -c Release

    - name: Pack Core.JsonSerializer
      run: dotnet pack ./Core.JsonSerializer.slnx --no-build -o ~/nuget -c Release

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push ~/nuget/*.nupkg
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NUGET_SECRET }}
        --skip-duplicate
